### ISSUE TITLE
wiki.en.bin cannot be opened for loading!

### ISSUE THREAD

**Issue by VicZlq** [woozzu/tagan#16]
hi!
I got an error when I tried to run sh scripts/test_flowers.sh
Traceback (most recent call last):
  File "test.py", line 42, in <module>
    word_embedding = fasttext.load_model(args.fasttext_model)
  File "/home/zhaoliuqing/anaconda3/lib/python3.7/site-packages/fasttext/FastText.py", line 363, in load_model
    return _FastText(model_path=path)
  File "/home/zhaoliuqing/anaconda3/lib/python3.7/site-packages/fasttext/FastText.py", line 43, in __init__
    self.f.loadModel(model_path)
ValueError: /home/zhaoliuqing/tagan-master/Volumes/ssd/fastText/wiki.en/wiki.en.bin cannot be opened for loading!
How can I solve it? thanks!

**Comment by woozzu** [comment]
@VicZlq The path seems wrong, please check if `/home/zhaoliuqing/tagan-master/Volumes/ssd/fastText/wiki.en/wiki.en.bin` is correct.
